services:

  qgis:
    depends_on: [db]
    build: ./
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix ro
      - ${PWD}/comptages:/root/.local/share/QGIS/QGIS3/profiles/default/python/plugins/comptages/
      - ${PWD}/test_data:/test_data
      - ${PWD}/test_outputs:/test_outputs
    command:
      - qgis
    environment:
      - DISPLAY=${DISPLAY}
    privileged: true
    network_mode: host

  qgis_tester:
    profiles: [local_test]
    depends_on: [db]
    build: 
      dockerfile: ./Dockerfile-test
    environment:
      LOCAL_TEST: 1
    command: sh -c 'xvfb-run python3 manage.py migrate && python3 manage.py test comptages.test -v2'
    volumes:
      - ${PWD}:/OpenComptage
      - ${PWD}/test_data:/test_data
      - ${PWD}/test_outputs:/test_outputs

  db:
    image: postgis/postgis:12-2.5
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=comptages
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgis-data:/var/lib/postgresql
    restart: "no"

volumes:
  postgis-data:
