[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "comptages"
version = "0.1"
dependencies = [
	"nose2 == 0.8.0",
	"psycopg2-binary == 2.8.6", # on Debian derivates this requires `libpq-dev`
	"icalendar == 4.0.3",
	"openpyxl == 3.1.2",
	"django == 3.2.15",
	"plotly == 5.3.1",
	"pandas == 1.3.4",
]

[project.optional-dependencies]
check = ["pyright>=1.1.36", "black>=23.11.0", "qgis-plugin-ci>=2.8.1"]

[tool.setuptools]
package-dir = { "" = "comptages" }

[tool.qgis-plugin-ci]
plugin_path = "comptages"
github_organization_slug = "opengisch"
project_slug = "OpenComptage"

[tool.pyright]
pythonVersion = "3.10"
exclude = ["**/nodes_modules", "**/__pycache__", "**/migrations"]
reportMissingImports = false
useLibraryCodeForTypes = true
