*OpenComptage* is a QGIS plugin to manage Canton Neuchâtel's /Comptages/
* Installation
** Development version
   Clone this repository with the submodules
   #+BEGIN_SRC sh
     git clone --recurse-submodules git@github.com:opengisch/OpenComptage.git
   #+END_SRC
   Go into the =scripts= directory of the repository
   #+BEGIN_SRC sh
     cd OpenComptage/scripts
   #+END_SRC
   Run the docker with the development database
   #+BEGIN_SRC sh
     ./start_docker.sh
   #+END_SRC
   Create the database structure (needed to be done only the fist time)
   #+BEGIN_SRC sh
     ./create_db.sh
   #+END_SRC
   Populate the development database
   #+BEGIN_SRC sh
     ./insert_test_data.sh
   #+END_SRC
   Link the plugin directory (=comptages= directory inside the repository) to the
   QGIS plugin directory. E.g.:
   #+BEGIN_SRC sh
     ln -s /home/mario/OpenComptage/comptages /home/mario/.local/share/QGIS/QGIS3/profiles/default/python/plugins
   #+END_SRC
   Run QGIS and enable the plugin from the /plugin-manager/

   To completely reset the docker with all the data
   #+BEGIN_SRC sh
     cd .docker
     docker-compose -f docker-compose_dev_env.yml down --volume
   #+END_SRC
* Tests
  Functional tests are run inside a Docker container. The docker container is
  based on Ubuntu 18.04 with QGIS installed. The ~run_docker_test.sh~ script, copy
  the plugin directory into the shared volume ~.docker/tests/~ and launches the
  ~run_test.sh~ script inside the docker container to run QGIS without welcome
  messages and execute into QGIS the ~test.py~ python script containing the
  tests. After a wait of 10s, a screenshot of the virtual framebuffer is taken,
  and stored into the shared volume as ~screenshot.png~, and the docker
  terminates.

  To run the tests, go to the ~scripts~ directory and do
  #+BEGIN_SRC sh
    ./run_test_on_docker.sh
  #+END_SRC
  To rebuild the docker, e.g. when the run_test.sh script is modified
  #+BEGIN_SRC sh
    docker-compose -f .docker/docker-compose.yml build
  #+END_SRC
* Other documents
** Engineering
   [[https://github.com/opengisch/comptages/blob/master/docs/engineering.org][Engineering documentation]]
