# Generated by Django 3.2.4 on 2021-09-03 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comptages', '0011_tjm_week_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tjm',
            name='day',
        ),
    ]
