# Generated by Django 3.2.4 on 2021-10-01 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptages', '0012_remove_tjm_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tjm',
            name='week_day',
        ),
        migrations.AddField(
            model_name='tjm',
            name='day',
            field=models.DateField(null=True),
        ),
    ]
