# Generated by Django 3.2.4 on 2021-08-20 06:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("comptages", "0002_search_path"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="id_category",
        ),
    ]
