# Generated by Django 3.2.4 on 2021-06-09 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comptages", "0002_search_path"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BaseTjmOk",
        ),
    ]
