# Generated by Django 3.2.4 on 2021-08-20 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comptages', '0003_auto_20210820_0626'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BaseTjmOk',
        ),
    ]
