# Generated by Django 3.2.4 on 2021-08-20 08:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comptages", "0004_delete_basetjmok"),
    ]

    operations = [
        migrations.AddField(
            model_name="countdetail",
            name="from_aggregate",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="countdetail",
            name="times",
            field=models.IntegerField(default=1),
        ),
    ]
