# Generated by Django 3.2.4 on 2021-08-20 11:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("comptages", "0005_auto_20210820_0843"),
    ]

    operations = [
        migrations.AddField(
            model_name="classcategory",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name="classcategory",
            name="id_class",
            field=models.ForeignKey(
                db_column="id_class",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="comptages.class",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="classcategory",
            unique_together=set(),
        ),
    ]
