# Generated by Django 3.2.4 on 2021-08-20 11:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('comptages', '0007_alter_classcategory_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensortypeclass',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='sensortypeinstallation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='sensortypemodel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='sensortypeclass',
            name='id_sensor_type',
            field=models.ForeignKey(db_column='id_sensor_type', on_delete=django.db.models.deletion.DO_NOTHING, to='comptages.sensortype'),
        ),
        migrations.AlterField(
            model_name='sensortypeinstallation',
            name='id_sensor_type',
            field=models.ForeignKey(db_column='id_sensor_type', on_delete=django.db.models.deletion.DO_NOTHING, to='comptages.sensortype'),
        ),
        migrations.AlterField(
            model_name='sensortypemodel',
            name='id_sensor_type',
            field=models.ForeignKey(db_column='id_sensor_type', on_delete=django.db.models.deletion.DO_NOTHING, to='comptages.sensortype'),
        ),
        migrations.AlterUniqueTogether(
            name='sensortypeclass',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='sensortypeinstallation',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='sensortypemodel',
            unique_together=set(),
        ),
    ]
