# Generated by Django 3.2.4 on 2021-09-03 08:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comptages", "0010_tjm"),
    ]

    operations = [
        migrations.AddField(
            model_name="tjm",
            name="week_day",
            field=models.SmallIntegerField(default=0),
        ),
    ]
