# Generated by Django 3.2.4 on 2021-10-29 05:55

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("comptages", "0015_sector"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sector",
            name="geometry",
            field=django.contrib.gis.db.models.fields.PolygonField(
                blank=True, null=True, srid=2056
            ),
        ),
    ]
