# Generated by Django 3.2.4 on 2021-11-01 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comptages', '0018_alter_countdetail_id_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tjm',
            name='count',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='count_of_tjm', to='comptages.count'),
        ),
    ]
