# Generated by Django 3.2.4 on 2021-11-01 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comptages', '0019_alter_tjm_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='id_class',
            field=models.ForeignKey(db_column='id_class', null=True, on_delete=django.db.models.deletion.CASCADE, to='comptages.class'),
        ),
    ]
