# Generated by Django 3.2.4 on 2021-11-14 10:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("comptages", "0019_alter_tjm_count"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Tjm",
        ),
    ]
