# Generated by Django 3.2.5 on 2022-01-14 05:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comptages", "0022_auto_20211217_0624"),
    ]

    operations = [
        migrations.AddField(
            model_name="installation",
            name="alias",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
