# Generated by Django 3.2.5 on 2022-02-03 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptages', '0023_installation_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='trash',
            field=models.BooleanField(default=False),
        ),
    ]
