# Generated by Django 3.2.5 on 2022-08-29 12:50

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptages', '0027_default_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=2056)),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'municipality',
            },
        ),
    ]
