name: Docker

on:
  push:
    branches:
      - '*'

  # pull_request:
  #   branches:
  #     - master

jobs:
  ci:
    name: CI
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Install requirements
        run: |
          pip3 install -r requirements.txt
        
      - name: Start docker stack
        run: docker-compose up --build -d

      - name: Wait a little bit
        run: sleep 5

      - name: Running migrations
        run: python manage.py migrate

      - name: Running tests
        run: |
          python manage.py test comptages.test -v2
