name: Docker

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Start docker stack
        run: docker compose up db -d

      - name: Running tests
        run: docker compose run qgis_tester
