name: Release

on:
  release:
    types:
      - published

jobs:
  release:
    runs-on: ubuntu-22.04
    name: Package / Release plugin
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Setup
        run: pip install qgis-plugin-ci

      - name: Package
        id: package
        run: |
          latest_tag=${GITHUB_REF#refs/*/}
          qgis-plugin-ci package $latest_tag
          echo "latest_tag=${latest_tag}" >> $GITHUB_OUTPUT

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: comptages.${{ steps.package.outputs.latest_tag }}.zip
          overwrite: true
